-- =====================================================================
--  Matemática Sin Estrés - Esquema físico de la base de datos
--  Migración V1 (Flyway). Compatible con PostgreSQL 14+ y H2 (modo PostgreSQL).
--  Convenciones: snake_case, PK sustitutas IDENTITY, FK con nombre explícito,
--  restricciones CHECK para reglas de dominio e índices sobre FK consultadas.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ROLES: perfiles de autorización (ADMIN, ALUMNO)
-- ---------------------------------------------------------------------
CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR(30)  NOT NULL,
    descripcion  VARCHAR(150),
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- 2. USUARIOS: cuentas del sistema. La contraseña se guarda SOLO como hash BCrypt.
-- ---------------------------------------------------------------------
CREATE TABLE usuarios (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_completo    VARCHAR(120) NOT NULL,
    username           VARCHAR(40)  NOT NULL,
    email              VARCHAR(120) NOT NULL,
    password_hash      VARCHAR(100) NOT NULL,
    rol_id             BIGINT       NOT NULL,
    activo             BOOLEAN      NOT NULL DEFAULT TRUE,
    intentos_fallidos  INTEGER      NOT NULL DEFAULT 0,
    bloqueado_hasta    TIMESTAMP,
    ultimo_acceso      TIMESTAMP,
    creado_en          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_username UNIQUE (username),
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles (id),
    CONSTRAINT ck_usuarios_intentos CHECK (intentos_fallidos >= 0)
);
CREATE INDEX idx_usuarios_rol ON usuarios (rol_id);

-- ---------------------------------------------------------------------
-- 3. NIVELES: programas académicos (Primaria, Secundaria, Preuniversitario)
-- ---------------------------------------------------------------------
CREATE TABLE niveles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo          VARCHAR(20)  NOT NULL,
    nombre          VARCHAR(60)  NOT NULL,
    subtitulo       VARCHAR(160),
    rango_edad      VARCHAR(60),
    precio_mensual  NUMERIC(8,2) NOT NULL,
    destacado       BOOLEAN      NOT NULL DEFAULT FALSE,
    orden           INTEGER      NOT NULL DEFAULT 0,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_niveles PRIMARY KEY (id),
    CONSTRAINT uq_niveles_codigo UNIQUE (codigo),
    CONSTRAINT ck_niveles_precio CHECK (precio_mensual >= 0)
);

-- ---------------------------------------------------------------------
-- 4. NIVEL_CARACTERISTICAS: beneficios que se muestran por nivel (1:N)
-- ---------------------------------------------------------------------
CREATE TABLE nivel_caracteristicas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nivel_id     BIGINT       NOT NULL,
    descripcion  VARCHAR(160) NOT NULL,
    orden        INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_nivel_caracteristicas PRIMARY KEY (id),
    CONSTRAINT fk_caracteristicas_nivel FOREIGN KEY (nivel_id) REFERENCES niveles (id) ON DELETE CASCADE
);
CREATE INDEX idx_caracteristicas_nivel ON nivel_caracteristicas (nivel_id);

-- ---------------------------------------------------------------------
-- 5. HORARIOS: turnos de clase en vivo
-- ---------------------------------------------------------------------
CREATE TABLE horarios (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    turno        VARCHAR(20) NOT NULL,
    hora_inicio  TIME        NOT NULL,
    hora_fin     TIME        NOT NULL,
    dias         VARCHAR(60) NOT NULL,
    CONSTRAINT pk_horarios PRIMARY KEY (id),
    CONSTRAINT uq_horarios_turno UNIQUE (turno),
    CONSTRAINT ck_horarios_rango CHECK (hora_fin > hora_inicio)
);

-- ---------------------------------------------------------------------
-- 6. CLASES_GRABADAS: sesiones grabadas (solo visibles para alumnos con matrícula activa)
-- ---------------------------------------------------------------------
CREATE TABLE clases_grabadas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo            VARCHAR(150) NOT NULL,
    descripcion       VARCHAR(500),
    nivel_id          BIGINT       NOT NULL,
    duracion_minutos  INTEGER      NOT NULL,
    fecha_clase       DATE         NOT NULL,
    url_video         VARCHAR(300) NOT NULL,
    url_pizarra       VARCHAR(300),
    publicada         BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_por        BIGINT,
    creado_en         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_clases_grabadas PRIMARY KEY (id),
    CONSTRAINT fk_clases_nivel FOREIGN KEY (nivel_id) REFERENCES niveles (id),
    CONSTRAINT fk_clases_creador FOREIGN KEY (creado_por) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_clases_duracion CHECK (duracion_minutos > 0)
);
CREATE INDEX idx_clases_nivel ON clases_grabadas (nivel_id);
CREATE INDEX idx_clases_fecha ON clases_grabadas (fecha_clase);

-- ---------------------------------------------------------------------
-- 7. MATRICULAS: relación alumno - nivel - horario con su estado
-- ---------------------------------------------------------------------
CREATE TABLE matriculas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT      NOT NULL,
    nivel_id        BIGINT      NOT NULL,
    horario_id      BIGINT      NOT NULL,
    estado          VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
    fecha_inicio    DATE,
    fecha_fin       DATE,
    creado_en       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_matriculas PRIMARY KEY (id),
    CONSTRAINT fk_matriculas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_matriculas_nivel FOREIGN KEY (nivel_id) REFERENCES niveles (id),
    CONSTRAINT fk_matriculas_horario FOREIGN KEY (horario_id) REFERENCES horarios (id),
    CONSTRAINT ck_matriculas_estado CHECK (estado IN ('PENDIENTE', 'ACTIVA', 'VENCIDA', 'ANULADA')),
    CONSTRAINT ck_matriculas_fechas CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX idx_matriculas_usuario ON matriculas (usuario_id);
CREATE INDEX idx_matriculas_nivel ON matriculas (nivel_id);

-- ---------------------------------------------------------------------
-- 8. SOLICITUDES_INFORMACION: formulario público "clase de diagnóstico gratis"
-- ---------------------------------------------------------------------
CREATE TABLE solicitudes_informacion (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(100) NOT NULL,
    telefono   VARCHAR(15)  NOT NULL,
    email      VARCHAR(120),
    nivel_id   BIGINT,
    mensaje    VARCHAR(500),
    atendida   BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_solicitudes PRIMARY KEY (id),
    CONSTRAINT fk_solicitudes_nivel FOREIGN KEY (nivel_id) REFERENCES niveles (id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------------
-- 9. AUDITORIA_ACCESOS: bitácora de eventos de seguridad (login, bloqueos, registros)
-- ---------------------------------------------------------------------
CREATE TABLE auditoria_accesos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id     BIGINT,
    identificador  VARCHAR(120),
    evento         VARCHAR(30)  NOT NULL,
    detalle        VARCHAR(255),
    ip             VARCHAR(45),
    creado_en      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditoria PRIMARY KEY (id),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
);
CREATE INDEX idx_auditoria_fecha ON auditoria_accesos (creado_en);
