-- =====================================================================
--  Migración V4: progreso del alumno en las clases grabadas
--  Permite marcar una clase como vista, guardarla como favorita y
--  recordar la última clase abierta ("Continuar viendo").
-- =====================================================================
CREATE TABLE progreso_clases (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT    NOT NULL,
    clase_id        BIGINT    NOT NULL,
    vista           BOOLEAN   NOT NULL DEFAULT FALSE,
    favorita        BOOLEAN   NOT NULL DEFAULT FALSE,
    ultima_vez      TIMESTAMP,
    actualizado_en  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_progreso_clases PRIMARY KEY (id),
    CONSTRAINT uq_progreso_usuario_clase UNIQUE (usuario_id, clase_id),
    CONSTRAINT fk_progreso_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_progreso_clase FOREIGN KEY (clase_id) REFERENCES clases_grabadas (id) ON DELETE CASCADE
);
CREATE INDEX idx_progreso_usuario ON progreso_clases (usuario_id);
CREATE INDEX idx_progreso_clase ON progreso_clases (clase_id);
