package pe.matematicasinestres.api.entity;

public enum EventoAuditoria {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    CUENTA_BLOQUEADA,
    LOGIN_CUENTA_BLOQUEADA,
    LOGIN_CUENTA_INACTIVA,
    REGISTRO,
    CAMBIO_PASSWORD,
    CUENTA_DESBLOQUEADA,
    CUENTA_DESACTIVADA,
    CUENTA_ACTIVADA,
    PASSWORD_RESTABLECIDA
}
